---
title: "Ratfish_markdown"
output: html_document
---



##Data

```{r}
ratfish_data <- read.csv("../data/Copy of JonMcLean_Ratfish_Tow_Location_Densities(4824).csv")

```

##Required packages

```{r}
library(tidyverse)
```

##Rounded Latitudes and Longitudes down to one decimal place
```{r}
ratfish_data_rounded <- mutate(ratfish_data, rounded_latitude = round(StartLatitude_DD, digits = 1), rounded_longitude = round(StartLongitude_DD, digits = 1)) 
```




#Latitude graph
```{r, echo = FALSE}
ggplot(ratfish_data_rounded, aes(rounded_latitude, Ratfish_BiomassDensity.kg.ha.)) +
  geom_bar(stat = "summary", fun.y = "mean") +
  theme_classic() +
  labs(x = "latitude", y = "Ratfish Biomass", title = "Ratfish Biomass and Latitude")
  

```


#Longtitude graph
```{r, echo = FALSE}
ggplot(ratfish_data_rounded, aes(rounded_longitude, Ratfish_BiomassDensity.kg.ha.)) +
  geom_bar(stat = "summary", fun.y = "mean") +
  theme_classic() +
  labs(x = "Longitude", y = "Ratfish Biomass", title = "Ratfish Biomass and Longitude")


```